# Generated by Django 5.2.3 on 2025-07-19 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('primary', 'Asosiy tashxis'), ('secondary', "Qo'shimcha tashxis"), ('differential', 'Differentsial tashxis'), ('provisional', 'Dastlabki tashxis')], default='primary', max_length=20, verbose_name='Tashxis turi')),
                ('diagnosis_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='ICD-10 kod')),
                ('diagnosis_name', models.CharField(max_length=200, verbose_name='Tashxis nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('confidence_level', models.CharField(choices=[('confirmed', 'Tasdiqlangan'), ('probable', 'Ehtimoliy'), ('possible', 'Mumkin'), ('ruled_out', 'Istisno qilingan')], default='probable', max_length=20, verbose_name='Ishonch darajasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Tashxis',
                'verbose_name_plural': 'Tashxislar',
                'ordering': ['diagnosis_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='Dori nomi')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dozasi')),
                ('frequency', models.CharField(max_length=100, verbose_name='Qabul qilish chastotasi')),
                ('duration', models.CharField(max_length=100, verbose_name='Qabul qilish muddati')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name="Ko'rsatmalar")),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name="Nojo'ya ta'sirlar")),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='Qarshlashuvlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Retsept',
                'verbose_name_plural': 'Retseptlar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('lifestyle', 'Turmush tarzi'), ('diet', 'Parhez'), ('exercise', 'Jismoniy mashqlar'), ('follow_up', "Takroriy ko'rik"), ('test', 'Tahlil'), ('specialist', "Mutaxassis ko'rigi"), ('procedure', 'Protsedura')], max_length=20, verbose_name='Tavsiya turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=10, verbose_name='Muhimlik')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name="Takroriy ko'rik sanasi")),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Tavsiya',
                'verbose_name_plural': 'Tavsiyalar',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Umumiy baho')),
                ('professionalism_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Professionallik')),
                ('communication_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Muloqot')),
                ('punctuality_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Vaqtni saqlash')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sarlavha')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Sharh')),
                ('would_recommend', models.BooleanField(verbose_name='Tavsiya qilasizmi?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('phone', 'Telefon'), ('video', 'Video'), ('home_visit', 'Uyga tashrif')], default='online', max_length=20, verbose_name='Konsultatsiya turi')),
                ('status', models.CharField(choices=[('scheduled', 'Rejalashtirilgan'), ('in_progress', 'Jarayonda'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan'), ('no_show', 'Kelmagan'), ('rescheduled', 'Qayta rejalashtirilgan')], default='scheduled', max_length=20, verbose_name='Holat')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', 'Oddiy'), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='normal', max_length=10, verbose_name='Muhimlik darajasi')),
                ('scheduled_date', models.DateField(verbose_name='Rejalashtirilgan sana')),
                ('scheduled_time', models.TimeField(verbose_name='Rejalashtirilgan vaqt')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Davomiyligi (daqiqa)')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy boshlanish vaqti')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Haqiqiy tugash vaqti')),
                ('chief_complaint', models.TextField(verbose_name='Asosiy shikoyat')),
                ('symptoms', models.TextField(blank=True, null=True, verbose_name='Simptomlar')),
                ('symptom_duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Simptomlar davomiyligi')),
                ('current_medications', models.TextField(blank=True, null=True, verbose_name='Hozirgi dorilar')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='Allergiyalar')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Konsultatsiya narxi')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chegirma miqdori')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yakuniy summa')),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langan")),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name="To'lov usuli")),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('referral_reason', models.TextField(blank=True, null=True, verbose_name='Yuborish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Bekor qilish sababi')),
                ('chat_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='chat.chatsession', verbose_name='Chat sessiyasi')),
            ],
            options={
                'verbose_name': 'Konsultatsiya',
                'verbose_name_plural': 'Konsultatsiyalar',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
    ]
