# Generated by Django 5.2.3 on 2025-07-19 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'blank': 'Telefon raqam kiritilishi shart.', 'null': 'Telefon raqam kiritilishi shart.', 'unique': "Bu telefon raqam allaqachon ro'yxatdan o'tgan."}, help_text="Telefon raqam +998901234567 formatida bo'lishi kerak", max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam'),
        ),
    ]
