# Generated by Django 5.2.3 on 2025-09-10 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0012_rename_lattitude_doctor_latitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('complaint_type', models.CharField(choices=[('general', 'General'), ('service', 'Service'), ('billing', 'Billing')], default='service', max_length=50)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='in_progress', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Complaint',
                'verbose_name_plural': 'Doctor Complaints',
                'db_table': 'doctor_complaint',
            },
        ),
        migrations.CreateModel(
            name='DoctorComplaintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaint_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='admin_panel.doctorcomplaint')),
            ],
            options={
                'verbose_name': 'Doctor Complaint File',
                'verbose_name_plural': 'Doctor Complaint Files',
                'db_table': 'doctor_complaint_file',
            },
        ),
    ]
