# Generated by Django 5.2.3 on 2025-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcomplaint',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
