# Generated by Django 5.2.3 on 2025-07-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('terapevt', 'Terapevt'), ('stomatolog', 'Stomatolog'), ('kardiolog', 'Kardiolog'), ('urolog', 'Urolog'), ('ginekolog', 'Ginekolog'), ('pediatr', 'Pediatr'), ('dermatolog', 'Dermatolog'), ('nevrolog', 'Nevrolog'), ('oftalmolog', 'Oftalmolog'), ('lor', 'LOR (Quloq-Burun-Tomoq)'), ('ortoped', 'Ortoped'), ('psixiatr', 'Psixiatr'), ('endokrinolog', 'Endokrinolog'), ('gastroenterolog', 'Gastroenterolog'), ('pulmonolog', 'Pulmonolog')], max_length=50, verbose_name='Mutaxassislik')),
                ('degree', models.CharField(choices=[('oliy', 'Oliy toifa'), ('birinchi', 'Birinchi toifa'), ('ikkinchi', 'Ikkinchi toifa'), ('yoshlar', 'Yoshlar toifasi')], default='yoshlar', max_length=20, verbose_name='Toifa')),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Tajriba (yil)')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Litsenziya raqami')),
                ('education', models.TextField(verbose_name="Ta'lim")),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Yutuqlar')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografiya')),
                ('workplace', models.CharField(max_length=200, verbose_name='Ish joyi')),
                ('workplace_address', models.TextField(blank=True, null=True, verbose_name='Ish joyi manzili')),
                ('consultation_price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Konsultatsiya narxi')),
                ('diploma_image', models.ImageField(blank=True, null=True, upload_to='doctors/diplomas/', verbose_name='Diploma rasmi')),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='doctors/licenses/', verbose_name='Litsenziya rasmi')),
                ('certificate_images', models.JSONField(blank=True, default=list, verbose_name='Sertifikat rasmlari')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('is_online_consultation', models.BooleanField(default=True, verbose_name='Online konsultatsiya')),
                ('work_start_time', models.TimeField(blank=True, null=True, verbose_name='Ish boshlanish vaqti')),
                ('work_end_time', models.TimeField(blank=True, null=True, verbose_name='Ish tugash vaqti')),
                ('work_days', models.JSONField(default=list, help_text="Masalan: ['monday', 'tuesday', 'wednesday']", verbose_name='Ish kunlari')),
                ('verification_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('suspended', "To'xtatilgan")], default='pending', max_length=20, verbose_name='Tasdiq holati')),
                ('verification_documents_submitted', models.BooleanField(default=False, verbose_name='Hujjatlar topshirilgan')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin eslatmalari')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Reyting')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='Jami sharhlar')),
                ('total_consultations', models.PositiveIntegerField(default=0, verbose_name='Jami konsultatsiyalar')),
                ('successful_consultations', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli konsultatsiyalar')),
                ('profile_views', models.PositiveIntegerField(default=0, verbose_name="Profil ko'rishlar")),
                ('weekly_views', models.PositiveIntegerField(default=0, verbose_name="Haftalik ko'rishlar")),
                ('monthly_views', models.PositiveIntegerField(default=0, verbose_name="Oylik ko'rishlar")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Shifokor',
                'verbose_name_plural': 'Shifokorlar',
                'ordering': ['-rating', '-total_reviews', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba'), ('sunday', 'Yakshanba')], max_length=10, verbose_name='Kun')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Tanaffus boshlanishi')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='Tanaffus tugashi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjud')),
                ('max_patients', models.PositiveIntegerField(default=20, verbose_name='Maksimal bemorlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Shifokor jadvali',
                'verbose_name_plural': 'Shifokor jadvallari',
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=100, verbose_name='Mutaxassislik nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='doctors/specializations/', verbose_name='Sertifikat rasmi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': "Qo'shimcha mutaxassislik",
                'verbose_name_plural': "Qo'shimcha mutaxassisliklar",
            },
        ),
        migrations.CreateModel(
            name='DoctorViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('daily_views', models.PositiveIntegerField(default=0, verbose_name="Kunlik ko'rishlar")),
                ('unique_visitors', models.PositiveIntegerField(default=0, verbose_name='Yagona ziyoratchilar')),
                ('visitor_regions', models.JSONField(default=dict, verbose_name='Ziyoratchilar viloyatlari')),
                ('referral_sources', models.JSONField(default=dict, verbose_name='Havola manbalari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': "Ko'rish statistikasi",
                'verbose_name_plural': "Ko'rish statistikalari",
                'ordering': ['-date'],
            },
        ),
    ]
