# Generated by Django 5.2.3 on 2025-07-19 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor', verbose_name='Shifokor'),
        ),
        migrations.AddField(
            model_name='doctorspecialization',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='doctors.doctor', verbose_name='Shifokor'),
        ),
        migrations.AddField(
            model_name='doctorviewstatistics',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_statistics', to='doctors.doctor', verbose_name='Shifokor'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty'], name='doctors_doc_special_4b2702_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['verification_status'], name='doctors_doc_verific_9eec10_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='doctors_doc_is_avai_e473c5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['rating'], name='doctors_doc_rating_d2720f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['hospital'], name='doctors_doc_hospita_823fc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'weekday')},
        ),
        migrations.AlterUniqueTogether(
            name='doctorviewstatistics',
            unique_together={('doctor', 'date')},
        ),
    ]
