# Generated by Django 5.2.3 on 2025-07-25 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('consultations', '0003_initial'),
        ('doctors', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(default=dict, verbose_name='Tarjimalar')),
                ('source_language', models.CharField(default='uzn_Latn', max_length=10, verbose_name='Manba til')),
                ('auto_detected_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Aniqlangan til')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chat.chatmessage', verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Xabar tarjimasi',
                'verbose_name_plural': 'Xabar tarjimalari',
            },
        ),
        migrations.CreateModel(
            name='ConsultationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(default=dict, verbose_name='Tarjimalar')),
                ('source_language', models.CharField(default='uzn_Latn', max_length=10, verbose_name='Manba til')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='consultations.consultation', verbose_name='Konsultatsiya')),
            ],
            options={
                'verbose_name': 'Konsultatsiya tarjimasi',
                'verbose_name_plural': 'Konsultatsiya tarjimalari',
            },
        ),
        migrations.CreateModel(
            name='DoctorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(default=dict, help_text='All field translations in different languages', verbose_name='Tarjimalar')),
                ('source_language', models.CharField(default='uzn_Latn', max_length=10, verbose_name='Manba til')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish')),
                ('is_auto_translated', models.BooleanField(default=True, verbose_name='Avtomatik tarjima')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='doctors.doctor', verbose_name='Shifokor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctor_translations', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi')),
            ],
            options={
                'verbose_name': 'Shifokor tarjimasi',
                'verbose_name_plural': 'Shifokor tarjimalari',
                'ordering': ['-last_updated'],
            },
        ),
    ]
