# Generated by Django 5.2.3 on 2025-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_chatmessagetranslation_consultationtranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='diploma_image',
            field=models.FileField(blank=True, null=True, upload_to='doctors/diplomas/', verbose_name='Diploma rasmi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Litsenziya raqami'),
        ),
    ]
