# Generated by Django 5.2.3 on 2025-08-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_diploma_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Litsenziya raqami'),
        ),
    ]
