# Generated by Django 5.2.3 on 2025-08-22 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctor_license_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Xizmat nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Shifokor xizmat nomi',
                'verbose_name_plural': 'Shifokor xizmat nomlari',
            },
        ),
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Narxi')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Xizmatning davomiyligi daqiqalarda', verbose_name='Davomiyligi (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctors.doctor', verbose_name='Shifokor')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_services', to='doctors.doctorservicename', verbose_name='Xizmat nomi')),
            ],
            options={
                'verbose_name': 'Shifokor xizmati',
                'verbose_name_plural': 'Shifokor xizmatlari',
                'unique_together': {('doctor', 'name')},
            },
        ),
    ]
