# Generated by Django 5.2.3 on 2025-08-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_doctorservicename_doctorservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='certificate_images',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='diploma_image',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_image',
        ),
        migrations.CreateModel(
            name='DoctorFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('diploma', 'Diploma'), ('license', 'Litsenziya'), ('certificate', 'Sertifikat')], max_length=20, verbose_name='Hujjat turi')),
                ('file', models.FileField(help_text="PDF, JPG, PNG formatlarida bo'lishi mumkin", upload_to='doctors/documents/', verbose_name='Hujjat fayli')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='doctors.doctor', verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Shifokor hujjati',
                'verbose_name_plural': 'Shifokor hujjatlari',
                'unique_together': {('doctor', 'file_type')},
            },
        ),
    ]
