# Generated by Django 5.2.3 on 2025-08-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_remove_doctor_certificate_images_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorfiles',
            unique_together=set(),
        ),
    ]
