# Generated by Django 5.2.3 on 2025-08-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctorfiles_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorfiles',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='doctors.doctor', verbose_name='Shifokor'),
        ),
    ]
