# Generated by Django 5.2.3 on 2025-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctorfiles_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lattitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uzunlik'),
        ),
    ]
