# Generated by Django 5.2.3 on 2025-09-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_doctor_lattitude_doctor_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
