# Generated by Django 5.2.3 on 2025-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_rename_lattitude_doctor_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorservicename',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xizmat nomi (Inglizcha)'),
        ),
        migrations.AddField(
            model_name='doctorservicename',
            name='name_kr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xizmat nomi (Krill)'),
        ),
        migrations.AddField(
            model_name='doctorservicename',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xizmat nomi (Ruscha)'),
        ),
    ]
