# Generated by Django 5.2.3 on 2025-07-19 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Shifoxona nomi')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Qisqa nomi')),
                ('hospital_type', models.CharField(choices=[('government', 'Davlat'), ('private', 'Xususiy'), ('clinic', 'Klinika'), ('polyclinic', 'Poliklinika'), ('hospital', 'Kasalxona'), ('medical_center', 'Tibbiy markaz')], default='clinic', max_length=20, verbose_name='Shifoxona turi')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda", regex='^\\+998\\d{9}$')], verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('services', models.TextField(blank=True, null=True, verbose_name='Xizmatlar')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospitals/logos/', verbose_name='Logo')),
                ('total_doctors', models.PositiveIntegerField(default=0, verbose_name='Jami shifokorlar')),
                ('total_patients', models.PositiveIntegerField(default=0, verbose_name='Jami bemorlar')),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Reyting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Shifoxona',
                'verbose_name_plural': 'Shifoxonalar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['region', 'district'], name='hospitals_h_region_737802_idx'), models.Index(fields=['hospital_type'], name='hospitals_h_hospita_acbdf6_idx'), models.Index(fields=['is_active', 'is_verified'], name='hospitals_h_is_acti_cdc390_idx')],
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Bo'lim nomi")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qavat')),
                ('room_numbers', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xona raqamlari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('head_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='doctors.doctor', verbose_name='Bosh shifokor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital', verbose_name='Shifoxona')),
            ],
            options={
                'verbose_name': "Shifoxona bo'limi",
                'verbose_name_plural': "Shifoxona bo'limlari",
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HospitalStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('active_doctors', models.PositiveIntegerField(default=0, verbose_name='Faol shifokorlar')),
                ('new_doctors', models.PositiveIntegerField(default=0, verbose_name='Yangi shifokorlar')),
                ('total_consultations', models.PositiveIntegerField(default=0, verbose_name='Jami konsultatsiyalar')),
                ('new_patients', models.PositiveIntegerField(default=0, verbose_name='Yangi bemorlar')),
                ('returning_patients', models.PositiveIntegerField(default=0, verbose_name='Qaytgan bemorlar')),
                ('online_consultations', models.PositiveIntegerField(default=0, verbose_name='Online konsultatsiyalar')),
                ('offline_consultations', models.PositiveIntegerField(default=0, verbose_name='Offline konsultatsiyalar')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami daromad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='hospitals.hospital', verbose_name='Shifoxona')),
            ],
            options={
                'verbose_name': 'Shifoxona statistikasi',
                'verbose_name_plural': 'Shifoxona statistikalari',
                'ordering': ['-date'],
                'unique_together': {('hospital', 'date')},
            },
        ),
    ]
