# Generated by Django 5.2.3 on 2025-08-21 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Tashkil etilgan yili'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('government', 'Davlat'), ('private', 'Xususiy'), ('clinic', 'Klinika'), ('polyclinic', 'Poliklinika'), ('hospital', 'Kasalxona'), ('medical_center', 'Tibbiy markaz'), ('labaratory', 'Laboratoriya')], default='clinic', max_length=20, verbose_name='Shifoxona turi'),
        ),
    ]
