# Generated by Django 5.2.3 on 2025-08-21 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_founded_year_alter_hospital_hospital_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='services',
        ),
        migrations.AddField(
            model_name='hospital',
            name='specialization',
            field=models.TextField(blank=True, help_text="Shifoxonaning asosiy ixtisoslashuvi yoki xizmatlari haqida ma'lumot", null=True, verbose_name='Ixtisoslashuvi'),
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Xizmatning davomiyligi daqiqalarda', verbose_name='Davomiyligi (daqiqa)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hospitals.hospital', verbose_name='Shifoxona')),
            ],
            options={
                'verbose_name': 'Shifoxona xizmati',
                'verbose_name_plural': 'Shifoxona xizmatlari',
                'unique_together': {('hospital', 'name')},
            },
        ),
    ]
