# Generated by Django 5.2.3 on 2025-09-06 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_regions_districts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hospital',
            new_name='hospitals_h_region__5f7dfc_idx',
            old_name='hospitals_h_region_737802_idx',
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.districts', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitals.regions'),
        ),
    ]
