# Generated by Django 5.2.3 on 2025-09-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_rename_hospitals_h_region_737802_idx_hospitals_h_region__5f7dfc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='working_days',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ish kunlari'),
        ),
    ]
