# Generated by Django 5.2.3 on 2025-09-06 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_hospital_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(default=dict, help_text='Tarjimalar JSON formatida saqlanadi', verbose_name='Tarjimalar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('is_auto_translated', models.BooleanField(default=False, verbose_name='Avtomatik tarjima qilingan')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='hospitals.hospital', verbose_name='Shifoxona')),
            ],
            options={
                'verbose_name': 'Shifoxona tarjimasi',
                'verbose_name_plural': 'Shifoxona tarjimalari',
                'ordering': ['-updated_at'],
            },
        ),
    ]
