# Generated by Django 5.2.3 on 2025-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_hospitaltranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='districts',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman nomi (Inglizcha)'),
        ),
        migrations.AddField(
            model_name='districts',
            name='name_kr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman nomi (Krillcha)'),
        ),
        migrations.AddField(
            model_name='districts',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman nomi (Ruscha)'),
        ),
        migrations.AddField(
            model_name='regions',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat nomi (Inglizcha)'),
        ),
        migrations.AddField(
            model_name='regions',
            name='name_kr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat nomi (Krillcha)'),
        ),
        migrations.AddField(
            model_name='regions',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat nomi (Ruscha)'),
        ),
    ]
