# Generated by Django 5.2.3 on 2025-07-19 12:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(choices=[(1, '1 - Juda yomon'), (2, '2 - Yomon'), (3, "3 - O'rtacha"), (4, '4 - Yaxshi'), (5, "5 - A'lo")], verbose_name='Umumiy baho')),
                ('ai_accuracy_rating', models.PositiveIntegerField(choices=[(1, '1 - Juda yomon'), (2, '2 - Yomon'), (3, "3 - O'rtacha"), (4, '4 - Yaxshi'), (5, "5 - A'lo")], verbose_name='AI aniqlik bahosi')),
                ('response_time_rating', models.PositiveIntegerField(choices=[(1, '1 - Juda yomon'), (2, '2 - Yomon'), (3, "3 - O'rtacha"), (4, '4 - Yaxshi'), (5, "5 - A'lo")], verbose_name='Javob tezligi bahosi')),
                ('positive_feedback', models.TextField(blank=True, null=True, verbose_name='Ijobiy fikr')),
                ('negative_feedback', models.TextField(blank=True, null=True, verbose_name='Salbiy fikr')),
                ('suggestions', models.TextField(blank=True, null=True, verbose_name='Takliflar')),
                ('would_recommend', models.BooleanField(verbose_name='Boshqalarga tavsiya qilasizmi?')),
                ('found_doctor', models.BooleanField(blank=True, null=True, verbose_name='Shifokor topdingizmi?')),
                ('contacted_doctor', models.BooleanField(blank=True, null=True, verbose_name="Shifokor bilan bog'landingizmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Chat fikr-mulohaza',
                'verbose_name_plural': 'Chat fikr-mulohazalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'Foydalanuvchi'), ('ai', 'AI Assistant'), ('system', 'Tizim')], max_length=10, verbose_name='Yuboruvchi turi')),
                ('message_type', models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('file', 'Fayl'), ('location', 'Joylashuv'), ('doctor_recommendation', 'Shifokor tavsiyasi'), ('system_info', "Tizim ma'lumoti")], default='text', max_length=23, verbose_name='Xabar turi')),
                ('content', models.TextField(verbose_name='Mazmun')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat/attachments/', verbose_name='Biriktirma')),
                ('ai_model_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ishlatilgan AI model')),
                ('ai_response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='AI javob vaqti (soniya)')),
                ('ai_tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ishlatilgan tokenlar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_important', models.BooleanField(default=False, verbose_name='Muhim')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Tahrirlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Tahrirlangan vaqt')),
            ],
            options={
                'verbose_name': 'Chat xabari',
                'verbose_name_plural': 'Chat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_ip', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('completed', 'Tugallangan'), ('cancelled', 'Bekor qilingan'), ('expired', 'Muddati tugagan')], default='active', max_length=20, verbose_name='Holat')),
                ('detected_specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Aniqlangan mutaxassislik')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ishonch darajasi')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Jami xabarlar soni')),
                ('user_messages_count', models.PositiveIntegerField(default=0, verbose_name='Foydalanuvchi xabarlari')),
                ('ai_messages_count', models.PositiveIntegerField(default=0, verbose_name='AI xabarlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (daqiqa)')),
                ('metadata', models.JSONField(blank=True, help_text="Session haqida qo'shimcha ma'lumotlar (til, qurilma turi va boshqalar)", null=True, verbose_name="Qo'shimcha ma'lumotlar")),
            ],
            options={
                'verbose_name': 'Chat sessiyasi',
                'verbose_name_plural': 'Chat sessiyalari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_doctors', models.JSONField(verbose_name='Tavsiya etilgan shifokorlar')),
                ('specialty', models.CharField(max_length=50, verbose_name='Mutaxassislik')),
                ('reason', models.TextField(verbose_name='Tavsiya sababi')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimal narx')),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True, verbose_name="Afzal ko'rilgan joylashuv")),
                ('online_consultation', models.BooleanField(default=False, verbose_name='Online konsultatsiya')),
                ('doctors_clicked', models.JSONField(blank=True, null=True, verbose_name='Bosilgan shifokorlar')),
                ('selected_doctor_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tanlangan shifokor ID')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name="Foydali bo'ldi")),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
            ],
            options={
                'verbose_name': 'Shifokor tavsiyasi',
                'verbose_name_plural': 'Shifokor tavsiylari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('symptom_classification', 'Simptom tasnifi'), ('specialty_detection', 'Mutaxassislik aniqlash'), ('urgency_assessment', 'Shoshilinchlik baholash'), ('general_advice', 'Umumiy maslahat')], max_length=30, verbose_name='Tahlil turi')),
                ('detected_keywords', models.JSONField(blank=True, null=True, verbose_name="Aniqlangan kalit so'zlar")),
                ('detected_symptoms', models.JSONField(blank=True, null=True, verbose_name='Aniqlangan simptomlar')),
                ('recommended_specialty', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tavsiya etilgan mutaxassislik')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Ishonch darajasi')),
                ('urgency_level', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('emergency', 'Favqulodda')], default='medium', max_length=20, verbose_name='Shoshilinchlik darajasi')),
                ('model_version', models.CharField(max_length=50, verbose_name='Model versiyasi')),
                ('processing_time', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='Tahlil vaqti (soniya)')),
                ('raw_response', models.TextField(verbose_name='Xom javob')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='chat.chatmessage', verbose_name='Tahlil qilingan xabar')),
            ],
            options={
                'verbose_name': 'AI tahlili',
                'verbose_name_plural': 'AI tahlilar',
                'ordering': ['-created_at'],
            },
        ),
    ]
